#version: '3.9'

services:
  ecommerce_app:
    container_name: ecommerce_app
    build: .
    ports:
      - 8080:8080
    volumes:
      - ecommerce_imagens:/app/uploads  
    environment:
      - DIRETORIO_IMAGENS=/app/uploads  
      - DATABASE_URL=jdbc:postgresql://aws-db.cs1vdo3kgx17.us-east-1.rds.amazonaws.com:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres*db
    depends_on:
      - ecommerce_db
    command: >
      sh -c "until pg_isready -h ecommerce_db -p 5432; do sleep 2; done &&
      java -jar /app-1.0.0.jar"
    networks:
      - aws-network

  ecommerce_db:
    container_name: ecommerce_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres*db
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aws-network

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin          
    ports:
      - "8081:80"  
    depends_on:
      - ecommerce_db
    networks:
      - aws-network

networks:
  aws-network:
    driver: bridge
    
volumes:
  pgdata: {}
  ecommerce_imagens: {}
